SU-8024 Event logs now have eaId and eaDisplayName
squaredup/SquaredUp.EAM.Library pull request #6
Opened 2019-12-20 14:28 UTC by nickwarms

When EA discovery is now run the events are now logged with the eaId and the eaDisplayName. These can be viewed in the event log. Main changes include: 
- Adding code to the `Start` section of the script to read the name and id from SCOM.
- Creating a logging section.
- Adding a function to log the information rather than calling `$SCRIPT:momapi.LogScriptEvent ` every time.
- Moving the Error log function into the logging section.

![image](https://user-images.githubusercontent.com/58977186/71260991-24bf2680-2334-11ea-8cb9-c5318d9dae20.png)

2020-02-27 11:00 UTC, shadeon requested changes
A couple of changes but otherwise looks good, thanks for improving this 😄

2020-02-27 11:00 UTC, shadeon commented on ManagementPacks/SquaredUp.EAM.Library/Modules/Scripts/SquaredUp.EAM.Discovery.ps1
> +	$eaDisplayName = $EA.DisplayName
This field often doesn't get updated correctly when singletons are renamed (SCOM bug) - would be safer to use the `DisplayName` property instead (available on all SCOM objects via inheritance from the `System.Entity` object).

2020-02-27 11:00 UTC, shadeon commented on ManagementPacks/SquaredUp.EAM.Library/Modules/Scripts/SquaredUp.EAM.Discovery.ps1
> +Write-InfoLog "Management Server pool: [`"$([string]::Join('", "', @($msInsts | %{ $_.DisplayName })))`"]"
Can you split this onto two lines so it's a bit less horrible to read 😉 
`$msInstsNames = $msInsts | Select -ExpandProperty DisplayName` is a nice way of doing it.

2020-02-27 11:00 UTC, shadeon commented on ManagementPacks/SquaredUp.EAM.Library/Modules/Scripts/SquaredUp.EAM.Discovery.ps1
> +	$app = $map.properties | Where-Object {$_.propertyId -match "\[Name='SquaredUpEAMLibrary!SquaredUp.EAM.Library.Class.Availability'\]/ApplicationId"}
The script parameter `$managedEntityId` is already the SCOM guid for the EA, so this is unnecessary and you can just use that directly.

2020-02-28 14:12 UTC, WaynePlummer approved these changes

2020-02-28 16:11 UTC, nickwarms commented on ManagementPacks/SquaredUp.EAM.Library/Modules/Scripts/SquaredUp.EAM.Discovery.ps1
> +	$eaDisplayName = $EA.DisplayName
I checked after doing a rename to an EA so this should be the correct entity now (Get-SCOMClass did not pick up the rename)

2020-03-02 08:42 UTC, shadeon approved these changes

2020-03-13 11:24 UTC, Parulmonpara commented
![SU-8024 Event log ](https://user-images.githubusercontent.com/61867498/76616975-26f0e580-651d-11ea-8e56-9ef19596c2f3.PNG)

2020-03-13 11:28 UTC, Parulmonpara approved these changes

2020-03-13 13:08 UTC, merged